try {
    let a = 5;
    let b = a + c
} catch (err) {
    console.log(err)
} finally {
    console.log("Hi")
}